theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Color scheme supports "light" (default) and "dark"
color_scheme: light
